CREATE TABLE CAR(MANUFACTURE VARCHAR(50) NOT NULL,MODEL VARCHAR(30) NOT NULL,PRICE INT NOT NULL);
SELECT * FROM CAR;
INSERT INTO CAR VALUES('TOYOTA','CAMRY',16000);
INSERT INTO CAR VALUES('TOYOTA','HIGHLANDER',22000);
INSERT INTO CAR VALUES('HONDA','PILOT',24000);
INSERT INTO CAR VALUES('HONDA','ACCORD',17000);



 SELECT distinct  a.MANUFACTURE,a.MODEL,a.PRICE FROM CAR a
 left join CAR b on a.MANUFACTURE = b.MANUFACTURE and a.PRICE < b.PRICE
 where b.MANUFACTURE is NULL;


 SELECT  MANUFACTURE,max(MODEL)as MODEL,max(PRICE) as PRICE FROM CAR group by MANUFACTURE;